FROM node:18-alpine as development

# Install dependencies needed for Prisma
RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/


# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]