version: '3.8'

services:
  app:
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/gbu_app
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - PRISMA_CLI_BINARY_TARGETS=linux-musl
    depends_on:
      - db
    volumes:
      - .:/app
      - dev_node_modules:/app/node_modules
    command: sh -c "npm ci && npx prisma generate && npm run dev"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=gbu_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dev_node_modules: